name: aamarpay
description: Official Flutter plugin for aamarPay. aamarPay is an online payment gateway service for Bangladesh.
version: 1.0.5
homepage: https://github.com/sanjidbillah/aamarpay

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.4
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
